#!/usr/bin/env python3
"""Render a swatch and type specimen page for each design direction.

Writes ``gallery/specimens/<direction>.html`` plus an index, using tokens
generated by the skill's own ``tokens.py``. Regenerate after changing any
direction file.

Standard library only. Exit code 0 on success, 2 for a usage error.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL = REPO_ROOT / "skills" / "aurelium-ui"
DIRECTIONS_DIR = SKILL / "assets" / "directions"
OUT_DIR = REPO_ROOT / "gallery" / "specimens"

SWATCH_ORDER = [
    "page", "surface", "surface-raised", "border",
    "text", "text-muted", "accent", "accent-hover", "accent-fg", "focus",
    "success", "warning", "danger", "info",
]

TYPE_STEPS = ["5xl", "4xl", "3xl", "2xl", "xl", "lg", "base", "xs", "2xs"]

SPECIMEN_LINE = "The quiet confidence of a considered interface"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise SystemExit("cannot load {0}".format(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


tokens_module = load_module("tokens", SKILL / "scripts" / "tokens.py")
contrast_module = load_module("contrast", SKILL / "scripts" / "contrast.py")


PAGE_CSS = """
*, *::before, *::after { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--color-page);
  color: var(--color-text);
  font-family: var(--font-body);
  font-size: var(--text-base);
  line-height: var(--leading-base);
  -webkit-font-smoothing: antialiased;
}

.wrap {
  max-inline-size: 72rem;
  margin-inline: auto;
  padding: var(--space-8) var(--space-5) var(--space-11);
}

header { margin-block-end: var(--space-9); }

h1 {
  font-family: var(--font-display);
  font-size: var(--text-4xl);
  line-height: var(--leading-4xl);
  letter-spacing: var(--tracking-4xl);
  margin: 0 0 var(--space-2);
}

.lede { color: var(--color-text-muted); max-inline-size: 60ch; margin: 0; }

h2 {
  font-size: var(--text-xs);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--color-text-muted);
  font-weight: 600;
  margin: var(--space-9) 0 var(--space-4);
  padding-block-end: var(--space-2);
  border-block-end: 1px solid var(--color-border);
}

.swatches {
  display: grid;
  gap: var(--space-4);
  grid-template-columns: repeat(auto-fill, minmax(min(100%, 11rem), 1fr));
  list-style: none;
  padding: 0;
  margin: 0;
}

.swatch { display: grid; gap: var(--space-2); }

.chip {
  block-size: 4.5rem;
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border);
}

.swatch code {
  font-family: var(--font-mono, monospace);
  font-size: var(--text-2xs);
  color: var(--color-text-muted);
}

.swatch b { font-weight: 600; font-size: var(--text-xs); }

.type-row {
  display: grid;
  grid-template-columns: 5.5rem 1fr;
  gap: var(--space-4);
  align-items: baseline;
  padding-block: var(--space-3);
  border-block-end: 1px solid var(--color-border);
}

.type-row code {
  font-family: var(--font-mono, monospace);
  font-size: var(--text-2xs);
  color: var(--color-text-muted);
}

.specimen { margin: 0; overflow-wrap: anywhere; }

.display-face { font-family: var(--font-display); }

.panels {
  display: grid;
  gap: var(--space-5);
  grid-template-columns: repeat(auto-fit, minmax(min(100%, 14rem), 1fr));
}

.panel {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-5);
}

.panel h3 { margin: 0 0 var(--space-2); font-size: var(--text-base); }
.panel p { margin: 0; color: var(--color-text-muted); font-size: var(--text-xs); }

.btn-row { display: flex; flex-wrap: wrap; gap: var(--space-3); align-items: center; }

.btn {
  font: inherit;
  font-weight: 600;
  font-size: var(--text-xs);
  padding: var(--space-3) var(--space-5);
  border-radius: var(--radius-md);
  border: 1px solid transparent;
  cursor: pointer;
  min-block-size: 44px;
  transition: background var(--duration-fast) var(--ease-standard);
}

.btn-primary { background: var(--color-accent); color: var(--color-accent-fg); }
.btn-primary:hover { background: var(--color-accent-hover); }

.btn-secondary {
  background: transparent;
  color: var(--color-text);
  border-color: var(--color-border);
}

:focus-visible {
  outline: 2px solid var(--color-focus);
  outline-offset: 2px;
}

table { border-collapse: collapse; inline-size: 100%; font-size: var(--text-xs); }
th, td { text-align: start; padding: var(--space-3) var(--space-2);
         border-block-end: 1px solid var(--color-border); }
th { color: var(--color-text-muted); font-weight: 600; }
td.num { text-align: end; font-family: var(--font-mono, monospace);
         font-variant-numeric: tabular-nums lining-nums; }

.meta { display: grid; gap: var(--space-2); font-size: var(--text-xs); margin: 0; }
.meta div { display: flex; gap: var(--space-3); }
.meta dt { color: var(--color-text-muted); min-inline-size: 7rem; }
.meta dd { margin: 0; font-family: var(--font-mono, monospace); }

.toggle {
  position: fixed;
  inset-block-start: var(--space-4);
  inset-inline-end: var(--space-4);
  z-index: 10;
}

.pairs { font-size: var(--text-xs); }
.pairs li { margin-block-end: var(--space-1); }
.ok { color: var(--color-success); font-weight: 600; }

.nav { display: flex; flex-wrap: wrap; gap: var(--space-3); font-size: var(--text-xs); }

/* Every link takes the accent. Without this the browser default blue lands on
   a near-black surface in dark mode and fails contrast. */
a { color: var(--color-accent); text-underline-offset: 0.2em; }
a:hover { color: var(--color-accent-hover); }

@media (prefers-reduced-motion: reduce) {
  * { transition-duration: 1ms !important; }
}
"""

TOGGLE_SCRIPT = """
(function () {
  var key = "aurelium-specimen-theme";
  var button = document.querySelector(".toggle");
  function apply(theme) {
    document.documentElement.setAttribute("data-theme", theme);
    button.textContent = theme === "dark" ? "Light theme" : "Dark theme";
    button.setAttribute("aria-pressed", theme === "dark" ? "true" : "false");
  }
  var stored = null;
  try { stored = localStorage.getItem(key); } catch (error) { stored = null; }
  var initial = stored || (window.matchMedia &&
    window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  apply(initial);
  button.addEventListener("click", function () {
    var next = document.documentElement.getAttribute("data-theme") === "dark"
      ? "light" : "dark";
    apply(next);
    try { localStorage.setItem(key, next); } catch (error) { /* private mode */ }
  });
})();
"""


def font_link(fonts: Dict[str, str]) -> str:
    """Build a Google Fonts link so the specimen shows the real faces.

    Without this the page falls back to a system serif, which defeats the
    purpose of a type specimen.
    """
    families = []
    seen = set()
    for role in ("display", "body", "mono"):
        family = fonts.get(role)
        if not family or family in seen:
            continue
        seen.add(family)
        weights = "300;400;500;600;700" if role != "mono" else "400;500"
        families.append(
            "family={0}:wght@{1}".format(family.replace(" ", "+"), weights)
        )
    if not families:
        return ""
    return (
        '<link rel="preconnect" href="https://fonts.googleapis.com" />\n'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n'
        '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?{0}'
        '&amp;display=swap" />'.format("&amp;".join(families))
    )


def escape(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def theme_css(direction: Dict[str, object]) -> str:
    """Light by default, dark under both the media query and the data attribute."""
    built = tokens_module.build_tokens(direction, opulence=6, density=5, motion=6)
    return tokens_module.format_css(built, "auto")


def swatch_markup(colors: Dict[str, str]) -> str:
    items = []
    for name in SWATCH_ORDER:
        if name not in colors:
            continue
        items.append(
            '<li class="swatch">'
            '<div class="chip" style="background: var(--color-{0})"></div>'
            "<b>{0}</b><code>{1}</code>"
            "</li>".format(escape(name), escape(colors[name]))
        )
    return "\n".join(items)


def type_markup(fonts: Dict[str, str]) -> str:
    rows = []
    for step in TYPE_STEPS:
        display = step in ("5xl", "4xl", "3xl")
        face = ' display-face' if display else ""
        rows.append(
            '<div class="type-row">'
            "<code>{0}</code>"
            '<p class="specimen{1}" style="font-size: var(--text-{0});'
            " line-height: var(--leading-{0});"
            ' letter-spacing: var(--tracking-{0})">{2}</p>'
            "</div>".format(escape(step), face, escape(SPECIMEN_LINE))
        )
    return "\n".join(rows)


def pairs_markup(direction: Dict[str, object]) -> str:
    items = []
    for pair in direction.get("contrast_pairs", []):
        palette = direction["colors"][pair["theme"]]
        ratio = contrast_module.contrast_ratio(
            contrast_module.parse_color(palette[pair["fg"]]),
            contrast_module.parse_color(palette[pair["bg"]]),
        )
        items.append(
            "<li>{0} on {1} <em>({2})</em> "
            '<span class="ok">{3:.2f}:1</span> needs {4}:1</li>'.format(
                escape(pair["fg"]),
                escape(pair["bg"]),
                escape(pair["theme"]),
                ratio,
                pair.get("min", 4.5),
            )
        )
    return "\n".join(items)


def render_specimen(direction: Dict[str, object], names: List[str]) -> str:
    name = direction["name"]
    others = " ".join(
        '<a href="{0}.html">{0}</a>'.format(escape(other))
        for other in names
        if other != name
    )
    motion = direction["motion"]
    meta_rows = [
        ("Display", direction["fonts"].get("display", "none")),
        ("Body", direction["fonts"].get("body", "none")),
        ("Mono", direction["fonts"].get("mono", "none")),
        ("Type base", "{0}px".format(direction["type"]["base"])),
        ("Type ratio", direction["type"]["ratio"]),
        ("Spacing base", "{0}px".format(direction["spacing"]["base"])),
        ("Radius md", direction["radii"].get("md", "0")),
        ("Duration base", motion["durations"].get("base", "n/a")),
        ("Ease standard", motion["easings"].get("standard", "n/a")),
    ]
    meta = "\n".join(
        "<div><dt>{0}</dt><dd>{1}</dd></div>".format(escape(label), escape(value))
        for label, value in meta_rows
    )

    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{label} specimen</title>
{fonts}
<style>
{tokens}
{page}
</style>
</head>
<body>
<button class="toggle btn btn-secondary" type="button" aria-pressed="false">Dark theme</button>
<div class="wrap">
<header>
  <h1>{label}</h1>
  <p class="lede">{mood}. Every colour pair below is verified against WCAG AA in
  both themes by the repository validator.</p>
</header>

<h2>Palette</h2>
<ul class="swatches">
{swatches}
</ul>

<h2>Type scale</h2>
{type_rows}

<h2>Surfaces and controls</h2>
<div class="panels">
  <div class="panel">
    <h3>Raised surface</h3>
    <p>A panel sitting on the page, separated by a hairline.</p>
  </div>
  <div class="panel" style="box-shadow: var(--shadow-e2)">
    <h3>Overlay</h3>
    <p>The elevation used for popovers and dropdowns.</p>
  </div>
  <div class="panel">
    <h3>Actions</h3>
    <div class="btn-row">
      <button class="btn btn-primary" type="button">Primary</button>
      <button class="btn btn-secondary" type="button">Secondary</button>
    </div>
  </div>
</div>

<h2>Tabular figures</h2>
<table>
  <thead><tr><th>Account</th><th>Reference</th><th class="num">Amount</th></tr></thead>
  <tbody>
    <tr><td>Operating</td><td>INV-2291</td><td class="num">12,480.00</td></tr>
    <tr><td>Reserve</td><td>INV-2292</td><td class="num">1,118.50</td></tr>
    <tr><td>Payroll</td><td>INV-2293</td><td class="num">96,204.75</td></tr>
  </tbody>
</table>

<h2>Tokens</h2>
<dl class="meta">
{meta}
</dl>

<h2>Verified contrast</h2>
<ul class="pairs">
{pairs}
</ul>

<h2>Other directions</h2>
<p class="nav"><a href="index.html">All specimens</a> {others}</p>
</div>
<script>
{script}
</script>
</body>
</html>
""".format(
        label=escape(direction["label"]),
        fonts=font_link(direction["fonts"]),
        mood=escape(direction["mood"]),
        tokens=theme_css(direction),
        page=PAGE_CSS,
        swatches=swatch_markup(direction["colors"]["light"]),
        type_rows=type_markup(direction["fonts"]),
        meta=meta,
        pairs=pairs_markup(direction),
        others=others,
        script=TOGGLE_SCRIPT,
    )


def render_index(directions: List[Dict[str, object]]) -> str:
    cards = []
    for direction in directions:
        light = direction["colors"]["light"]
        chips = "".join(
            '<span title="{1}" style="display:inline-block;inline-size:1.75rem;'
            "block-size:1.75rem;border-radius:4px;background:{0};"
            'border:1px solid var(--color-border)"></span>'.format(
                escape(light[key]), escape(key)
            )
            for key in ("page", "surface", "text", "accent")
        )
        cards.append(
            '<li class="panel">'
            '<h3><a href="{0}.html">{1}</a></h3>'
            "<p>{2}</p>"
            '<div style="display:flex;gap:.5rem;margin-block-start:1rem">{3}</div>'
            "</li>".format(
                escape(direction["name"]),
                escape(direction["label"]),
                escape(direction["mood"]),
                chips,
            )
        )

    first = directions[0]
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Aurelium UI specimens</title>
{fonts}
<style>
{tokens}
{page}
.swatches {{ list-style: none; }}
</style>
</head>
<body>
<button class="toggle btn btn-secondary" type="button" aria-pressed="false">Dark theme</button>
<div class="wrap">
<header>
  <h1>Design direction specimens</h1>
  <p class="lede">Five complete systems. Open each to review its palette, type
  scale, surfaces, and verified contrast in both themes.</p>
</header>
<ul class="swatches">
{cards}
</ul>
</div>
<script>
{script}
</script>
</body>
</html>
""".format(
        tokens=theme_css(first),
        fonts=font_link(first["fonts"]),
        page=PAGE_CSS,
        cards="\n".join(cards),
        script=TOGGLE_SCRIPT,
    )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="build_specimens.py",
        description="Render swatch and type specimen pages for each direction.",
    )
    parser.add_argument(
        "--out", type=Path, default=OUT_DIR, help="Output directory."
    )
    args = parser.parse_args(argv)

    names = tokens_module.available_directions(DIRECTIONS_DIR)
    if not names:
        print("error: no direction files found", file=sys.stderr)
        return 2

    args.out.mkdir(parents=True, exist_ok=True)
    directions = [tokens_module.load_direction(name, DIRECTIONS_DIR) for name in names]

    for direction in directions:
        path = args.out / "{0}.html".format(direction["name"])
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(render_specimen(direction, names))
        print("wrote", path.relative_to(REPO_ROOT).as_posix())

    index_path = args.out / "index.html"
    with open(index_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_index(directions))
    print("wrote", index_path.relative_to(REPO_ROOT).as_posix())

    return 0


if __name__ == "__main__":
    sys.exit(main())
